checkformat:clangformat:
  stage: checkformat
  image: ubuntu:23.10
  only:
    - merge_requests
  allow_failure: true
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y
    - apt-get install -y --no-install-recommends git clang-format clang-format-17
  script:
    - ./scripts/format.sh
    - git --no-pager diff --exit-code HEAD
